#---------------------------------------------------------------------------------------------------
#Note Counter Script designed by Paul Kasay at King's College London
#The script is meant to take a file path from previously created notes directory
#And counts each reblog occurence, exporting the results to a .csv file
#---------------------------------------------------------------------------------------------------

import re
import os
from bs4 import BeautifulSoup
import collections
import csv


#the function counter is defined and takes the full path of notes directory generated by the extraction script
#the text file is then found, opened, and read in
def counter(notes_path):
    notes_location = notes_path + "/Notes.txt"
    recorded_notes = file(notes_location, 'r')
    notes = recorded_notes.read()

    #regular expressions sort the list items into a python list
    #the collections counter parses through the list variable
    #and creates a collections object that can accept specialized methods
    reblogs = re.findall("reblogged this from <a class=\"source_tumblelog\" href=\"(.*?)\"", notes)
    counts = collections.Counter(reblogs)
    #most common is invoked and stored as an example and for convenience later, but is not used
    most_common = collections.Counter(reblogs).most_common(10)
    #the collection object is converted to a standard python dictionary
    count_data = dict(counts)
    #the terminal will print out the object data
    print counts

    #while the csv writer exports the dictionary to a csv text file
    writer = csv.writer(open('counter.csv', 'wb'))
    for key, value in count_data.items():
        writer.writerow([key, value])


#The script prompts the user for the directory path to the notes text file
counter(raw_input("What folder of notes would you like to parse through?"))
